FROM clojure:latest

RUN apt-get update
RUN apt-get -y install git-core
RUN apt-get -y install curl gnupg
# RUN curl -sL https://deb.nodesource.com/setup_16.x  | bash -
# RUN apt-get -y install nodejs
# RUN npm install